services:
  - type: web
    name: easybuy-web
    env: docker
    plan: free
    region: frankfurt # Or oregon, ohio, singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: EasyBuy
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:2VVHoZAy/C60UkdUBm3piMbiAF0Y/xCxsKAANOhAwNI=
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: array
      - key: RUN_SEEDERS
        value: "true"
      # Database connection automatically wired to the Render PostgreSQL database below
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: easybuy-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: easybuy-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: easybuy-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: easybuy-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: easybuy-db
          property: password

databases:
  - name: easybuy-db
    databaseName: easybuy
    user: easybuy_user
    plan: free
    region: frankfurt
